sudo: required
services:
  - docker

before_install:
  - docker build -t bartbruneel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bartbruneel/react-test npm test -- --coverage

after_success:
  - docker build -t bartbruneel/multi-client ./client
  - docker build -t bartbruneel/multi-nginx ./nginx
  - docker build -t bartbruneel/multi-server ./server
  - docker build -t bartbruneel/multi-worker ./worker

#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take the images and push to dockerhub
  - docker push bartbruneel/multi-client
  - docker push bartbruneel/multi-nginx
  - docker push bartbruneel/multi-server
  - docker push bartbruneel/multi-worker
